### ISSUE TITLE
$SHELL is not set properly for fish

### ISSUE THREAD

**Issue by what-the-functor** [LnL7/nix-darwin#146]
In fish shell with ```programs.fish.enable = true;```, the SHELL env var is set to bash in the nix store.  Whereas, in comparison with ```programs.zsh.enable = true```, whereas SHELL is set properly to zsh in the nix store.

**Comment by anrddh** [comment]
Any updates on this?

**Comment by malob** [comment]
I think this issue resolved or no longer relevant since https://github.com/LnL7/nix-darwin/commit/079db5db5bfe3565db104e8cac492feab5cf7889.

The `$SHELL` variable is no longer set when enabling any shell. You can just enable as many shells as you want, then set environment.variables.SHELL = "${pkgs.fish}/bin/fish" to make Fish your default shell.

**Comment by bestlem** [comment]
@malob setting $SHELL is not sufficient. You need to call chsh or dscl to chnage the shell.

**Comment by Enzime** [comment]
You don't want to manually set `$SHELL`, to make `fish` your default shell you can use:

```
users.users.<user>.shell = pkgs.fish;
```
