### ISSUE TITLE
Right way to add a custom package?

### ISSUE THREAD

**Issue by bkase** [LnL7/nix-darwin#16]
Hi, this project is amazing!

I have hacked together nix configs before, but I really would like to learn the "right" way to handle this situation. I'm opening an issue here because I think many people who use this project know nix very well:

Here is a snippet from my `~/.nixpkgs/darwin-configuration.nix` to add a custom prompt to zsh:

```
{ config, lib, pkgs, ... }:
let
  pureZshSrc = pkgs.fetchFromGitHub {
    owner = "bkase";
    repo = "pure";
    rev = "fdae02de51d940db59004ac93c24530cdb972376";
    sha256 = "1wp30lsqyz17swxhml2ryn7kx32kf8r1fcc244cwchzi77bwjv6c";
  };
  pureZsh = pkgs.stdenv.mkDerivation rec {
    name = "pure-zsh-${version}";
    version = "2017-03-04";
    src = pureZshSrc;

    installPhase = ''
      mkdir -p $out/share/zsh/site-functions
      cp pure.zsh $out/share/zsh/site-functions/prompt_pure_setup
      cp async.zsh $out/share/zsh/site-functions/async
    '';
  };
in
{
  environment.systemPackages =
    [ pkgs.nix-repl
      pureZsh
    ];

  programs.zsh.enable = true;
  programs.zsh.promptInit = ''
    # enable my pure prompt fork
    fpath+=( "${pureZsh.out}/share/zsh/site-functions" $fpath )

    autoload -U promptinit && promptinit
    prompt pure
  '';
/* ... */
```

This seems ugly for a few reasons:

1. I clearly shouldn't be inlining the definition the pure zsh prompt package. Would you recommend putting this in a separate file and importing it?
2. It feels strange to be doing a `stdenv.mkDerivation` just to rename a file. Is there a simpler way to do this?
3. Needing to extend `fpath` in the promptInit _seems_ wrong. And there is a coupling between the `pureZsh` system package and the promptInit.

It makes sense how to add something like `pureZsh` as a `mkOption` on the `zsh` program, but this is a fork of this prompt theme, so it seems like something that wouldn't be upstreamed and should be local to my `darwin-configuration.nix`.

Thanks in advance!

**Comment by LnL7** [comment]
Hopefully this clarifies some stuff. :smile:

1. There are a number of ways to introduce custom packages. I think defining it inline is fine depending on what you are doing, if you just want to put the definition in a separate file you can do something like this.

```nix
{ stdenv, fetchFromGitHub }:

stdenv.mkDerivation rec {
  name = "pure-zsh-${version}";
  version = "2017-03-04";

  src = fetchFromGitHub {
    owner = "bkase";
    repo = "pure";
    rev = "fdae02de51d940db59004ac93c24530cdb972376";
    sha256 = "1wp30lsqyz17swxhml2ryn7kx32kf8r1fcc244cwchzi77bwjv6c";
  };

  installPhase = ''
    mkdir -p $out/share/zsh/site-functions
    cp pure.zsh $out/share/zsh/site-functions/prompt_pure_setup
    cp async.zsh $out/share/zsh/site-functions/async
  '';
}
```

```nix
{ config, pkgs, ... }:
let
  pureZsh = pkgs.callPackage ./pkgs/pure-zsh {};
in

{
  environment.systemPackages =
    [ pkgs.nix-repl
      pureZsh
    ];
}
```

If you want the package to be available in a larger context (like other modules etc.) you can use overlays or packageOverrides

```nix
{ config, pkgs, ... }:

{
  environment.systemPackages =
    [ pkgs.nix-repl
      pkgs.pureZsh
    ];

  nixpkgs.config.packageOverrides = super: {
    pureZsh = pkgs.callPackage ./pkgs/pure-zsh {};
  };
}
```

2. Since the package has a source I think `stdenv.mkDerivation` is probably what you want. But you can disable some [phases](http://nixos.org/nixpkgs/manual/#sec-stdenv-phases) that you don't need or for very simple things there is `runCommand`, these are somewhat equivalent. If there's just a single phase you want to skip you should use `dontBuild = true;` instead of overriding all the phases.

```nix
runCommand "foo"
  { FOO = "Hello World!"; }
  ''
    echo $FOO > $out
  ''
```
```nix
stdenvNoCC.mkDerivation rec {
  name = "foo";
  phases = [ "installPhase" "fixupPhase" ];

  FOO = "Hello World!";

  installPhase = ''
    echo $FOO > $out
  '';
}
```

3. Agreed, an option for `fpath` probably makes sense, but any package with `$out/share/zsh/site-functions` should end up in the default fpath when installed in the system profile.

**Comment by bkase** [comment]
Great, thank you!
