### ISSUE TITLE
Wrong PATH set on emacs service

### ISSUE THREAD

**Issue by happysalada** [LnL7/nix-darwin#250]
When running emacs with the service, the PATH is set to the default macos PATH (something like `/usr/bin:/bin...`)
Emacs won't be able to find any of the executables installed with nix.

I've tried the workaround suggested here 
https://github.com/LnL7/nix-darwin/issues/52

which is 
`  launchd.user.envVariables.PATH = config.environment.systemPath;`
into the `darwin-configuration.nix`

That didn't work either. I'm not sure why. but when I run `get-env PATH` in emacs I still have the same default macos PATH.

@peel maybe you have a workaround?
(no rush if you're busy)

**Comment by LnL7** [comment]
I don't remember the exact semantics of launchd but I'm pretty sure this is different from the application issue described in #52. Unless the information from that issue is incomplete and the problem is also with the service there.

1. Launching applications from the UI means they'll inherit variables from the launchd user context, which I think includes variables set with launchd.

2. Services always run with an empty environment (similar to systemd), perhaps a bit confusing but launchd variables won't influence that. So for services PATH or any other environment variables should be defined in the service configuration. Take a look at the skhd service for example.
