### ISSUE TITLE
Recent changes in fish-foreign-env (Nixpkgs) break /etc/fish/nixos-env-preinit.fish

### ISSUE THREAD

**Issue by teehemkay** [LnL7/nix-darwin#269]
Basically, `fish-foreign-env` directory layout was changed in a recent `Nixpkgs` [commit](https://github.com/NixOS/nixpkgs/commit/99bfa4bb601bfc94a72296f0b2395a4f888e5d84).
This results in breakage in the `fish` expression in `nix-darwin` which assumes a [specific directory layout](https://github.com/LnL7/nix-darwin/blob/8834df431736c3037bbef017b24c62bc4ace4645/modules/programs/fish.nix#L109).

This results in a rather annoying breakage (no `darwin-nix` environment, no `nix` even) for those using `fish` as their default shell. One has to manually relink `/nix/var/nix/profiles/system` to a previous generation to restore a working nix-darwin environment.

**Comment by abathur** [comment]
This happened during the course of #107834, and https://github.com/NixOS/nixpkgs/pull/107834#issuecomment-752208683 explains that it is a breaking change, at least. I'm not fish-familiar so I don't have much insight here, but I wanted to cross-link it.

**Comment by kevingriffin** [comment]
Although fixing this is straightforward, I have a pull request open to reduce the dependency on fenv in nix-darwin. This speeds up shell startup by a lot, and depending on how much we're willing to change, it could even be removed completely. If you use fish, please have a look and give me some feedback:

https://github.com/LnL7/nix-darwin/pull/266

**Comment by teehemkay** [comment]
Thank you. I'll try and have a look this afternoon.

**Comment by toonn** [comment]
@kevingriffin, how would #266 deal with some substitutions fish doesn't have, `${VAR:-fallback}`, for example?
Maybe [babelfish](https://github.com/NixOS/nixpkgs/pull/107834#discussion_r549615685) could be used in addition/instead?

**Comment by kevingriffin** [comment]
@toonn Thank you for the feedback! In which attribute are you imagining those substitutions coming up? For the fish module of nix-darwin itself, #266 just requires you to set your configuration as fish instead of bash, and it transforms configured ENV variables into `set` statements.

Are you thinking about how to handle `extraInit` in the environment module? I'll see if I can wire up babelfish in my branch. 

I'm not sure what expectations other fish users have of this attribute, so I'd love to hear some use cases.

**Comment by kevingriffin** [comment]
@toonn I've opened #270 with babelfish. Give it a try and see what you think.

**Comment by toonn** [comment]
@kevingriffin, I was thinking about `environment.variables`. I'm not sure whether nix-darwin explicitly supports POSIX substitutions but I know h-m's environment stuff does, this came up in a related issue.

I'll try to check it out later today 👍

**Comment by malob** [comment]
Just wanted to chime into say that #270 looks really cool, and I'm excited for it to land. 

I did want to check though whether a quick minimal patch to `programs.fish` similar to what `home-manager` did in https://github.com/nix-community/home-manager/commit/e8358125d98fc0128a02b7664f532447750fb930, might make sense.

I added a [patched version](https://github.com/malob/nixpkgs/blob/master/darwin/modules/programs/fish.nix) of `programs.fish` in my config to address this in the short term, which just replaces all occurrences of `${pkgs.fish-foreign-env}/share/fish-foreign-env/functions` with `${pkgs.fishPlugins.foreign-env}/share/fish/vendor_functions.d`, and that seems to have worked (though I haven't tested it extensively):

**Comment by kevingriffin** [comment]
Hey @malob, thank you for having a look at #270!

I actually added a patch to update the path, but I didn't make it conditional as that commit did. Since the new version of the module that I'm working on over at https://github.com/NixOS/nixpkgs/pull/108947 will support both fenv and babelfish, it's a natural place to add that patch.

It seems like it might get merged over in nixOS tomorrow, and once it has been, I'll port back the changes to nix-darwin and integrate the fix from the home-manager commit. Sharing that helps a lot.
