### ISSUE TITLE
Error trying to enable spacebar service: error: The option `services.spacebar.package' is used but not defined. 

### ISSUE THREAD

**Issue by shaunsingh** [LnL7/nix-darwin#364]
Hi, I was drying to enable the spacebar service via the following: 
```nix
  # bar
  services.spacebar.enable = true;
```

However, when rebuilding it fails with this error: 
```
 λ darwin-rebuild switch -I darwin-config=$HOME/.nixpkgs/darwin-configuration.nix
building the system configuration...
warning: warning: Nix search path entry '/nix/var/nix/profiles/per-user/root/channels' does not exist, ignoring
error: The option `services.spacebar.package' is used but not defined.
(use '--show-trace' to show detailed location information)
```

Note that I'm using nix-unstable on an aarch64-darwin (m1) chip. 
The regular `spacebar` package installs and runs just fine, only the service has an error

**Comment by cmacrae** [comment]
@shaunsingh You need to explicitly declare which package to use with the module:
```
services.spacebar.enable = true;
services.spacebar.package = pkgs.spacebar;
```

This was done when I initially introduced the module because the package was in the unstable channel. However, this should probably change now, as the package has been available for some time in the stable release channels.
