### ISSUE TITLE
When using Flakes, using `imports` with `inputs` doesn't work

### ISSUE THREAD

**Issue by thiagokokada** [LnL7/nix-darwin#365]
Something that I am used to do and works in both NixOS and Home-Manager is to use `imports` to load modules from `inputs` inside my configuration. This works with the usage of either `specialArgs` (from NixOS) or `extraSpecialArgs` (from Home-Manager). For example (note that I am using HM here just as an example, it happens with other modules I tried too):

```nix
{
  inputs = { ... };
  outputs = {self, nixpkgs, home, ...}: {
    nixosConfigurations.test = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      specialArgs = { inherit self; foo = home; };
      modules = [
        ({ pkgs, self, foo, ... }: {
          imports = [
            # Those all works on NixOS
            # home.nixosModules.home-manager
            self.inputs.home.nixosModules.home-manager
            # foo.nixosModules.home-manager
          ];
          users.users.user = {
            isNormalUser = true;
          };
          home-manager.users.user = {
            programs.zsh.enable = true;
            home.stateVersion = "21.05";
          };
        })
      ];
    };
  };
}
```

Using this is very powerful since I can load the module inside a specific module (for example, I only load the `home.nixosModules.home-manager` when I do a `imports = [ ./home-manager ];`, that includes my whole Home Manager configuration).

However, on `nix-darwin` it seems that I can only import a module on either `modules = [];` or if there is a direct reference to the input. Using `inputs` argument from `lib.darwinSystem` (that is the thing that seems similar to `specialArgs` on NixOS) doesn't work, and results in an infinity recursion. If this is isn't clear, I hope the example below makes it clearer:

```nix
{
  inputs = { ... };
  outputs = {self, nixpkgs, home, ...}: {
    darwinConfigurations = {
      test = nix-darwin.lib.darwinSystem {
        system = "x86_64-darwin";
        inputs = {
          inherit self;
          foo = home;
        };
        modules = [
          # This works
          # home.darwinModules.home-manager
          ({ pkgs, self, foo, ... }: {
            imports = [
              # This also works (since it is using `home` directly from inputs)
              # home.darwinModules.home-manager
              # This doesn't work (infinite recursion encountered)
              self.inputs.home.darwinModules.home-manager
              # This also doesn't (infinite recursion encountered)
              # foo.darwinModules.home-manager
            ];
            users.users.user = {};
            home-manager.users.user = {
              programs.zsh.enable = true;
              home.stateVersion = "21.05";
            };
          })
        ];
      };
    };
  };
}
```

This is the error I got:

```
nix --experimental-features 'nix-command flakes'  build '.#darwinConfigurations.test.system'
error: infinite recursion encountered

       at /nix/store/98qhbl73jd311c7f630qn2g0b73ld2gp-source/lib/modules.nix:305:28:

          304|         builtins.addErrorContext (context name)
          305|           (args.${name} or config._module.args.${name})
             |                            ^
          306|       ) (lib.functionArgs f);
(use '--show-trace' to show detailed location information)
make: *** [Makefile:14: build-darwin-test] Error 1
```

To make it easier, I created a gist to reproduce the error: https://gist.github.com/thiagokokada/ea598c2147090abe8b7a787f844d84fa

**Comment by kubukoz** [comment]
@thiagokokada thanks for this, I was struggling to understand why my `inputs` were not working. I think the README is wrong though, as it says you can use `inputs` for this exact  thing.

**Comment by n8henrie** [comment]
I'm in this boat as well, just commenting with what seems to be working for me.

Oddly, in my case, this works for my NixOS machines:

```
      lib.nixosSystem {
        specialArgs.inputs = inputs;
...
```

In the config I'm importing:
```
{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:
```

Whereas my nix-darwin machine has to be like this:

```
          darwin.lib.darwinSystem {
            specialArgs = inputs;
```

Later in the config I'm importing:

```
{
  config,
  pkgs,
  lib,
  ...
} @ inputs: {
```

Almost everything else is nearly identical between my nix-darwin and NixOS configs (the flake part at least).

I think nix-darwin has a hard time (in part?) because I don't have `inputs.nixpkgs` (just `inputs.nixpkgs-stable`, `inputs.nixpkgs-unstable`, etc.); NixOS doesn't seem to have an issue.

I get infinite recursion errors, attribute missing errors (from importing `inputs.agenix` later in the config) or errors about being unable to find `nixpkgs` using any of the following:

- `_module.args = { inherit inputs; };`
- `specialArgs = { inherit inputs; };`
- `specialArgs.inputs = inputs;`

A little extra reading on the topic: https://blog.nobbz.dev/posts/2022-12-12-getting-inputs-to-modules-in-a-flake/

**Comment by n8henrie** [comment]
> Oddly, in my case, this works for my NixOS machines:
>         specialArgs.inputs = inputs;
> Whereas my nix-darwin machine has to be like this:
>             specialArgs = inputs;

It looks like the issue is here:

https://github.com/LnL7/nix-darwin/blob/87b9d090ad39b25b2400029c64825fc2a8868943/eval-config.nix#L37

which can be contrasted with the definition in nixos:

https://github.com/NixOS/nixpkgs/blob/463643afa8b70b153ef1728493afce53817514ff/nixos/lib/eval-config.nix#L57

I think this ends up *requiring* that I have a `inputs.nixpkgs` if I am passing `specialArgs.inputs`. I don't. Instead, I have `nixpkgs-stable` and `nixpkgs-unable`.

So it looks like in my case, as a workaround, I can use:

```
specialArgs.inputs = inputs // {nixpkgs = nixpkgs-stable;};
```
