### ISSUE TITLE
darwin-rebuild leaves `./result` symlink behind when using flakes

### ISSUE THREAD

**Issue by lilyball** [LnL7/nix-darwin#375]
When I use the `--flake` flag, `darwin-rebuild` ends up leaving a `./result` symlink behind for any action that involves a build. It looks like the script explicitly avoids adding `--no-out-link` when using `--flake` but I don't know why.

```console
❯ ls -F
❯ darwin-rebuild --flake darwin-config check
building the system configuration...
ok
❯ ls -F
result@
```

**Comment by ryantking** [comment]
Further, it's happened three times now that in deleting his folder, it screwed up my whole system and I've had to uninstall nix entirely and rebuild. Usually deleting it is fine, not sure what triggers these catastrophic events.

**Comment by ryantking** [comment]
@lilyball I fixed this myself on [my fork](https://github.com/ryantking/nix-darwin). Feel free to use it, I'll be keeping it up to date with any changes that come upstream until this fix is in then I can move back to upstream myself. You should be able to just replace `lnl7` with `ryantking` in your `flake.nix` and do a `darwin-rebuild switch --flake /your/flake`. I did a fresh nix install since my system got into a bad state so I did a full reinstall from scratch with my fork.

@LnL7 I'd be happy to PR my fix, but there's already an open one (https://github.com/LnL7/nix-darwin/pull/310), that I just lifted the fix from and based it off the most recent master.

**Comment by emilazy** [comment]
Should have been fixed by https://github.com/LnL7/nix-darwin/pull/578.
