### ISSUE TITLE
fish: Don't source the Nix configuration if it already has been sourced

### ISSUE THREAD

**Issue by cbarrett** [LnL7/nix-darwin#48]
(Part of the effort to kill [this line of code](https://github.com/LnL7/nix-darwin/blob/88a11d28f1d7da749ad47e5abd09712de99f0b96/modules/programs/fish.nix#L126) dead.)

**Comment by therealpxc** [comment]
All of the Nix environment setup scripts I've seen (in the `nix.sh` script of GNU+Linux, the environment on NixOS, the `nix-daemon.sh` script on macOS, and in nix-darwin) set PATH this way. I think it makes sense on initial startup, but we have to make sure it runs as early as possible and never twice. Take a look at the NixOS module for Fish and the fish package in nixpkgs for an example.

I think if we change the Fish package to source /etc/static/preinit-whatever.fish instead of in plain /etc, then nix-darwin can put the file in place and NixOS should be unaffected. Right now nix-darwin can't put the file where Fish expects because it doesn't (and shouldn't) own `/etc`.

**Comment by cbarrett** [comment]
@therealpxc That makes sense to me, I think. I understand what the NixOS things in the Fish package are doing, at any rate.

How do you suggest managing the tickets for this?

**Comment by therealpxc** [comment]
I think we should make the changes we want on the Nixpkgs side on a local checkout while we work out the nix-darwin stuff, then submit the PRs for both pieces. That way the PR for Nixpkgs can say 'this makes the following achievable in nix-darwin' instead of 'we hope this will enable us to do xyz for nix-darwin'.

**Comment by cbarrett** [comment]
@therealpxc Sounds good to me.

[What the fish package does](https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/programs/fish.nix#L118) looks reasonable to me. I'm assuming we don't export the __fish_nixos_*_sourced variables because the idea is that we reset things anew in subshells anyway?

**Comment by LnL7** [comment]
The other [shell modules](https://github.com/LnL7/nix-darwin/blob/master/modules/programs/bash.nix#L72) do something similar, but how is this related to setting `PATH`?

**Comment by therealpxc** [comment]
@cbarrett that's right.

@LnL7 The way that PATH is set is neither by appending nor pre-pending but straight-up setting PATH, so that if the Nix configuration stuff gets sourced after other things (like `nix-shell`, for example) try to set the PATH, it will be erased.

Since EDITOR also gets set this way, for example, it overrides the `~/.config/fish/conf.d/env.fish` snippet I have which sets it to `vim`, so I have to re-override it at the end `~/.config/fish/config.fish`, which gets sourced later, as a workaround.

**Comment by therealpxc** [comment]
And to make Nix-installed CLI programs available to snippets in `~/.config/fish/conf.d` and directories like it, the Nix stuff has to be sourced prior to shell initialization proper, which is what the `preinit` stuff in the Fish package and NixOS module take care of. This is because the conf.d stuff is sourced before config.fish and in alphanumeric order, so adding a Fish snippet for Nix init doesn't guarantee that it will execute first either.

**Comment by LnL7** [comment]
Fixed by https://github.com/LnL7/nix-darwin/pull/50
