### ISSUE TITLE
`/usr/share/terminfo` not included in `TERMINFO_DIRS`

### ISSUE THREAD

**Issue by n8henrie** [LnL7/nix-darwin#543]
Currently, by default, I'm getting `TERMINFO_DIRS` set as per below:

```console
$ echo -e  "${TERMINFO_DIRS//:/'\n'}"
/Users/n8henrie/.nix-profile/share/terminfo
/etc/profiles/per-user/n8henrie/share/terminfo
/run/current-system/sw/share/terminfo
/nix/var/nix/profiles/default/share/terminfo
```

Unfortunately this seems to be missing settings for `xterm-256color`, which is one of the available defaults in `Terminal.app`, and so switching to the default config breaks things like clearing the screen. Appending MacOS's default directory resolves the issue:

```nix
environment.variables.TERMINFO_DIRS = [ "/usr/share/terminfo" ];
```

(This also works: <https://github.com/LnL7/nix-darwin/issues/383>)

Should the MacOS system terminfo be included by default in `TERMINFO_DIRS`? I'm fairly new to nix, so no worries if this is contradicts the spirit of the project.

**Comment by lilyball** [comment]
I just ran into this. This problem was caused by #533, prior to that PR nix-darwin did not touch `TERMINFO_DIRS`. As a consequence of that PR, anything using that variable no longer sees the system-provided terminfo files.

I believe the correct fix is to update the current definition of `TERMINFO_DIRS` to include `/usr/share/terminfo` at the end (either that, or add another definition like the given workaround but specifies it with `mkAfter` to sort it to the end).
