### ISSUE TITLE
Add a pkg override example

### ISSUE THREAD

**Issue by yurrriq** [LnL7/nix-darwin#6]
I tried overriding the gitAndTools.hub package without success. It'd be nice to have a working example in the docs here.

**Comment by LnL7** [comment]
Ah, I see what happened here, the change to the url or rev of `fetchgit` is not important for nix.
Since you already have a downloaded version of hello with the "correct" sha in your nix store that will be used. (the source of hub-2.2.8 in this case)

Changing the sha to `0000000000000000000000000000000000000000000000000000` will make sure nix actually tries to download and verify the source.

**Comment by LnL7** [comment]
Or you can force nix to rebuild the source using the `--check` flag

```
nix-build -I darwin-config=/tmp/darwin-configuration.nix -A pkgs.gitAndTools.hub.src --check
```

**Comment by yurrriq** [comment]
Aha, thanks for the explanation. I still think it might be good to have an override example, but I can see how that might be out of scope for this project. Maybe a link to the relevant NixOS docs would suffice.

**Comment by LnL7** [comment]
The readme contains an example, feel free to add an example of a package update to the example configurations.

**Comment by yurrriq** [comment]
Oops. Yeah, that looks great. Thanks!
