### ISSUE TITLE
What is the proper way to handle damaged applications?

### ISSUE THREAD

**Issue by cuichenli** [LnL7/nix-darwin#622]
I’m having trouble opening an app that I installed via darwin-rebuild. I’m not sure what caused the issue, but I get a message saying that the package is damaged. I’m wondering what the proper way to handle this situation is. I’ve tried removing the entry via darwin-rebuild edit and then nix-collect-garbage, but I can still see the package under the /nix/store directory. I also tried removing it via nix-env --uninstall, but it failed to find the corresponding package. Can someone please help me with this? Thank you.
![image](https://user-images.githubusercontent.com/29245119/227440113-0332a636-addc-496e-94dc-9bfbba96a3bd.png)

**Comment by 2gn** [comment]
Although it is not very recommended in this project, but you can use Homebrew packages from nix-darwin module. And in most cases, Homebrew packages tend to be more stable than ones from Nixpkgs.
I install applications with GUI from Homebrew, and command-line applications from Nixpkgs and so far, they're working properly.

For more informations about how to use Homebrew from nix-darwin, please check [this](https://daiderd.com/nix-darwin/manual/index.html#opt-homebrew.enable) out

**Comment by reckenrode** [comment]
Are you running macOS 13?

macOS 13 changed Gatekeeper to check notarized apps when they launch even if they lack the quarantine xattr. See https://eclecticlight.co/2022/06/17/app-security-changes-coming-in-ventura/.

What’s happening here the fixup phase changes the shell scripts in the bundle to point to the nix store, which breaks the signature of Postman. Since it’s notarized, macOS identifies it as damaged and won’t run it.

I’ve opened NixOS/nixpkgs#226560 to fix.

**Comment by Enzime** [comment]
If macOS complains about opening applications, usually you can still launch the app through Privacy & Security settings in System Preferences. Once you click Open Anyway, it won't prompt again for that same binary

Documented below in the `Note:` section:

https://support.apple.com/en-au/guide/mac-help/mh40616/mac

**Comment by cuichenli** [comment]
I have switched to use brew for GUI applications now (as suggested by @2gn ) and it is working well.

>If macOS complains about opening applications, usually you can still launch the app through Privacy & Security settings in System Preferences. Once you click Open Anyway, it won't prompt again for that same binary

I don't think that was the case, given the error message was different. 

> macOS 13 changed Gatekeeper to check notarized apps when they launch even if they lack the quarantine xattr. See [eclecticlight.co/2022/06/17/app-security-changes-coming-in-ventura](https://eclecticlight.co/2022/06/17/app-security-changes-coming-in-ventura/).

I suspect that was the case, but given I can not reproduce the error now, I am not hundred percent sure. 

But anyway, I will close this ticket now. Thanks for all your helps!

**Comment by Enzime** [comment]
Just tested this, even though the error message is different to the article I linked the instructions are still the same:

![Screenshot 2023-05-31 at 4 11 38 pm](https://github.com/LnL7/nix-darwin/assets/10492681/e73a58b7-82e4-411c-a8b2-c24859b53780)

This shouldn't be an issue now it's fixed in Nixpkgs, just wanted to leave the instructions for other people to discover in the future
