### ISSUE TITLE
homebrew package as a runtime dependency

### ISSUE THREAD

**Issue by 2gn** [LnL7/nix-darwin#642]
There are some packages that are not supported to be built for nix on darwin systems. Although it's possible to solve each problems one by one, it's sometime easier ( and simpler ) to use binaries from homebrew, especially when a software is a proprietary.

So, I'd like to define homebrew packages as a runtime dependency (`nativeBuildInputs`). Is there any way to do this? If not, any plans on implementing this feature?

**Comment by andrewcrook** [comment]
Hi 

> to use binaries from homebrew, especially when a software is a proprietary.

As you know nix-darwin allows you to use Homebrew formulas, casks and mas (Apple App Store)
So yes you can use it.

https://daiderd.com/nix-darwin/manual/index.html#opt-homebrew.enable
https://daiderd.com/nix-darwin/manual/index.html#opt-homebrew.masApps

Personally, I use it for casks and mas applications.
I don't plan to continue using homebrew formulas in the future for the reasons explained below.

> Although it's possible to solve each problems one by one

Unfortunately, this is the best way. The issue is that using Homebrew formulas would make your nix setup impure.
You couldn’t guarantee that the same versions of brew packages would be found and used for future nix builds, therefore, it wouldn't be replicable. Homebrew Versions, doesn’t hold a huge backlog of software versions. Homebrew tends to use system wide dependencies when it comes to interpreters, dynamic libraries and headers. Version mismatches could cause build processes and installations to fail. It already does cause issues in Homebrew itself. Nix allows you to build an application selecting the versions of all required dependences both at build time and runtime. Also because Homebrew installs system wide its installations would  breakout of these build and development environments that you can build with nix.

>  (nativeBuildInputs). Is there any way to do this?

If you don't plan to share you could just install Homebrew packages via nix-darwin or use a build script with one of the hooks in the build process to install required formula via brew command line. If you plan to share I would highly recommend the long road of doing it properly, I also think it would be better of yourself in the longterm.

**Comment by 2gn** [comment]
I understand I should do that, but it's way too difficult for me to fix [chromium](https://duckduckgo.com/?q=!nixpkgs+chromium) for darwin.
I guess I should learn nix a bit more, or wait for someone to fix it.
Thanks anyways!

**Comment by andrewcrook** [comment]
> but it's way too difficult for me to fix [chromium](https://duckduckgo.com/?q=!nixpkgs+chromium) for darwin.

Chromium via homebrew is a Cask though,  it’s using a precompiled binary. 
You can just use the `homebrew.casks` option of `nix-darwin` to install if you wish

Or if you look at `brew edit chromium` and make a flake using similar steps.

I agree installing chrome from source then compiling is more of a challenge. 

But I think using brew cask and chromes autoupdates is perfectly fine,  unless its a dependency of another app which is unlikely because software that does depend on it tend to come with their own version of the chromium engine etc.
Chromes autoupdates also makes sense because with a web browser you tend to want to be on the latest version.

**Comment by 2gn** [comment]
> create a flake based on what brew edit chromium shows and version it

That might work. I'll try that, thanks.
