### ISSUE TITLE
Declaratively modify `/etc/hosts`

### ISSUE THREAD

**Issue by msanft** [LnL7/nix-darwin#683]
Hello there!

Is there a way to declaratively modify the `/etc/hosts` file, the same way as [`networking.extraHosts`](https://github.com/NixOS/nixpkgs/blob/b52f6ac65d27e21516e78bd87b41ea1c81eef8b6/nixos/modules/config/networking.nix#L45) would do it on NixOS? No option seems to be declared in the `nix-darwin` codebase, has anyone worked around this?

Cheers

**Comment by eliandoran** [comment]
@msanft , on my side I was able to use `environment.etc` to manually write the hosts file. Please make sure to backup the existing `hosts` file, just in case.

```nix
{
  environment.etc."hosts" = {
    copy = true;
    text = ''
      127.0.0.1	    localhost
      255.255.255.255 broadcasthost
      ::1             localhost

      // Rest of the hosts go here.
    '';
  }
}
```

This will replace the existing `/etc/hosts` file regardless of its content. Haven't tested if using a symlink works, making a copy should theoretically be safer since it's closer to what macOS expects of a hosts file.

**Comment by msanft** [comment]
Thanks @eliandoran!

I must've somehow missed the `environment.etc.*` option. Thanks for pointing me!
