### ISSUE TITLE
Sanitise PATH before installation/activation/etc.

### ISSUE THREAD

**Issue by kirelagin** [LnL7/nix-darwin#86]
I would like to present to you my case here.

So I am recovering my system from upgrading to Mojave, which means that I have a ton of broken binaries in my `$PATH`. The plan was to use an unupgraded Mac to build a bunch of useful derivations from the fixes nixpkgs tree and then use it as a binary cache for obtaining various bootstrap-level tools. I manually fixed `nix` first and then decided to configure everything else (the working nixpkgs commit and the substituter for bootstrap packages) using `nix-darwin`.

The problem is that activation scripts are using, for example, `grep` and I had `gnugrep` in my `$PATH` (because I like `gnugrep` and don’t like `grep` from macOS), but since this `grep` was broken, the activation scripts were crashing in multiple places and I spent quite a lot of time figuring out what was going on.

Wouldn’t it be better to bring everything we need for installation and activation with us? Or, at least, clean up `$PATH` by resetting it to the macOS default, so that we know exactly which tools we are using?

**Comment by LnL7** [comment]
The activation already prioritises binaries from the new system and coreutils from the new nixpkgs. I wouldn't clear PATH entirely since some system binaries might not be available from nixpkgs. But things like gnugrep should probably treated the same way as coreutils instead of depending on the impure system versions.

https://github.com/LnL7/nix-darwin/blob/e3281c90cffe5c979ae4eb7f066310a76a7e518f/modules/system/activation-scripts.nix#L43
