### ISSUE TITLE
What is the correct way to set nixpkgs.config in darwin-configuration.nix?

### ISSUE THREAD

**Issue by ben-z** [LnL7/nix-darwin#89]
When I place `nixpkgs.config.programs.tmux.enable = true;` in my `darwin-configuration.nix`, it doesn't seem to take effect and install https://github.com/NixOS/nixpkgs/blob/release-18.03/nixos/modules/programs/tmux.nix.

Here's a simplified version of my `darwin-configuration.nix`:

```nix 
{ config, lib, pkgs, ... }:
{
  # ...
  nixpkgs.config.programs.tmux.enable = true;
  # ...
}
```

I also tried to put `nixpkgs.config.programs.tmux.enable = true;` in `~/.nixpkgs/config.nix` but it still doesn't seem to take effect. 

What is the correct way to set `nixpkgs.config.programs`?

**Comment by elseym** [comment]
on a mac with nix-darwin you typically want to use `darwin-configuration.nix` unless you specified `darwin-config=some/other/file.nix` in your `$NIX_PATH`.

so, to enable `tmux`, maybe you could try:
```
{ config, lib, pkgs, ... }:
{
  # ...
  programs.tmux.enable = true;
  # ...
}
```
which corresponds to [the tmux module's enable option](https://github.com/LnL7/nix-darwin/blob/master/modules/programs/tmux.nix#L42). in this file you can also find the other options for the `tmux` module.

**Comment by ben-z** [comment]
Thanks for the response, @elseym! But I specifically want to enable [the tmux program in the nixpkgs repo](https://github.com/NixOS/nixpkgs/blob/release-18.03/nixos/modules/programs/tmux.nix) because it has a lot more granular configuration options. Any ideas on how to do that? On a NixOS machine `programs.tmux.enable = true` in `configuration.nix` seems to point to that program but on macos `darwin-configuration.nix` it points to the tmux program in this repo.

**Comment by elseym** [comment]
oh i seem to have misunderstood you, thanks for the clarification 🙂 

unfortunately, you can not use nixpkgs modules on darwin (i.e. macos) since they are tailored for linux (i.e. nixos). that means for example that generated configuration files wouldn't be written to the correct locations or services couldn't be set up because most of them depend on systemd, which is not available on the mac.

i think the correct approach here would be to implement the missing functionality in [nix-darwin's tmux module](https://github.com/LnL7/nix-darwin/blob/master/modules/programs/tmux.nix).

**Comment by ben-z** [comment]
Ah I see. Does that mean we won't be able to use any of the [programs here](https://github.com/NixOS/nixpkgs/tree/master/nixos/modules/programs) on Darwin without re-implementing them in this repo?

**Comment by LnL7** [comment]
Yes, the problem with sharing modules is that they can change values of any option defined in other modules. And I don't feel comfortable sharing activation snippets with nixos since those are potentially unsafe in a different context like macOS. The nix-darwin implementation for environment.etc explicitly does not replace existing files for example, since those might be part of the system and pretty important.

**Comment by LnL7** [comment]
As for the `nixpkgs.config` option, that's used when importing <nixpkgs>. This is used for things like allowing unfree packages to be used https://nixos.org/nixpkgs/manual/#chap-packageconfig.

**Comment by ben-z** [comment]
Thank you both for your insight! I cloned the repo locally and added an additional option to the tmux in this repo 😃

**Comment by bglgwyng** [comment]
> As for the `nixpkgs.config` option, that's used when importing `<nixpkgs>`. This is used for things like allowing unfree packages to be used https://nixos.org/nixpkgs/manual/#chap-packageconfig.

@LnL7  Could you explain it in more detail please? I'm using flake and just setting `nixpkgs.config.allowUnfree = true;` doesn't work. I don't understand how to apply the configuration in the link with nix-darwin.
